load_package project

# Create project
project_new system_top -overwrite

# Project settings
set_global_assignment -name FAMILY "MAX 10"
set_global_assignment -name DEVICE 10M50DAF484C7G
set_global_assignment -name TOP_LEVEL_ENTITY system_top
set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files

# Add either .qip or .qsys file, not both.
# For .qip, the system must first be generated by Platform Designer
#set_global_assignment -name QIP_FILE nios2_system/synthesis/nios2_system.qip
# If including the .qsys file, the system will be generated when compiling
# the project in Quartus. The .qsys file should be under version control.
set_global_assignment -name QSYS_FILE nios2_system.qsys


# Add vhdl files
set_global_assignment -name VHDL_FILE ../hdl/system_top.vhd

# Timing
set_global_assignment -name SDC_FILE system_top.sdc

# Pinning
source de10-lite_pinning.tcl

project_close


# For this script to work the following folder structure is required. 
# - quartus
#   - create_project.tcl
#   - nios2_system.qsys
#   - de10-lite_pinning.tcl
#   - system_top.sdc
# - hdl
#   - system_top.vhdl
#
# Acces the Nios II command shell and run the script create_project.tcl
# in the quaruts folder:
#   quartus_sh -t create_project.tcl
# Compile the project
#   quartus_sh --flow compile system_top
